Public Class cons
{
    Public  cons(){
        system.debug('sample');
    }
    Public  cons(string name){
        system.debug('vivek');
    }
     Public  cons(string name,string nams){
        system.debug('karthi');
         test1();
    }
    Public static void test1()
    {
        system.debug('test1');
    }
    Public string test2()
    {
        string s;
        system.debug('test2');
        return s;
    }
}